#!/usr/bin/env python3

import schubser
import argparse
from typing import List, Dict
import sys


def parse_args(args: List[str]) -> Dict[str, str]:
    parser = argparse.ArgumentParser()
    parser.add_argument("--token", type=str, help="Pushover app token", required=True)
    parser.add_argument("--user", type=str, help="Pushover app token", required=True)
    parser.add_argument(
        "--title", type=str, help="Message title to send", required=True
    )
    parser.add_argument("--body", type=str, help="Message body to send", required=True)
    parser.add_argument(
        "--priority", type=int, help="message priority, from -2 to 2", default=0
    )
    parser.add_argument("--retry", type=int, help="seconds between tries", default=30)
    parser.add_argument("--expire", type=int, help="seconds to expire", default=10_000)
    parser.add_argument(
        "--sound", type=str, help="name of sound to play", default="pushover"
    )

    return vars(parser.parse_args(args))


def main(args: List[str]):
    args = parse_args(args)
    pushover = schubser.Pushover(args.pop("token"), args.pop("user"))
    pushover.message(
        title=args["title"],
        msg=args["body"],
        priority=args["priority"],
        retry=args["retry"],
        expire=args["expire"],
        sound=args["sound"],
    )


if __name__ == "__main__":
    main(sys.argv[1:])
